"""
Django settings for B2B_v1 project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gltt*w!lqa9-q-au3#g!h97gaqs0+28o8o!d%xhrwuc3sd!)0!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#DEBUG = False

#ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'car',
    'search',
    'first_page',
    'account',
    'myadmin',
    'user',
    'publish_car',
    'collection',
    'message',
    'demand',
    'setting',
    'finding',
    'personal_center',
    'captcha',
    'weixin',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'B2B_v1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'B2B_v1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'carStackAdmin',
#        'USER': 'root',
#        'PASSWORD': 'mole8cula6r',
#        'HOST': '120.25.81.56',
#        'PORT': '3306',
#        'ATOMIC_REQUESTS': True, #数据库设置中加入'ATOMIC_REQUESTS': True选项, 就能将整个http request包裹在transaction中. 这样做的好处显而易见是是安全, 但 坏处则是性能可能会下降
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'b2b_v1',
        'USER': 'guyuanjun',
        'PASSWORD': '12353051',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Internationalizatio
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS =(
    os.path.join(BASE_DIR, 'static').replace('\\','/'),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\','/')


#数据库缓存
#timeout 默认的缓存有效时间,以秒计. 默认值是 300 秒(五分钟).
#max_entries 用于 简单缓存 及 数据库缓存 后端, 缓存的最大条目数(超出该数旧的缓存会被清除,默认值是 300).
CACHES={
    'default':{
        'BACKEND':'django.core.cache.backends.db.DatabaseCache',
        'LOCATION':'main_cache_table',
        'TIMEOUT':10,
        'OPTIONS':{
            'MAX_ENTRIES':2000
        }
    }
}

#SESSION_SAVE_EVERY_REQUEST = True
#SESSION_EXPIRE_AT_BROWSER_CLOSE=True
SESSION_COOKIE_AGE=3600 #60分钟



#邮件配置
#EMAIL_HOST = 'smtp.163.com'                 #SMTP地址
#EMAIL_PORT = 465                                   #SMTP端口
#EMAIL_HOST_USER = 'guyuanjun92@163.com'            #我自己的邮箱
#EMAIL_HOST_PASSWORD = 'gu1992'                  #我的邮箱密码

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

#EMAIL_HOST = 'smtp.qq.com'                 #SMTP地址
#EMAIL_PORT = 465                                   #SMTP端口
#EMAIL_HOST_USER = '1422297148@qq.com'            #我自己的邮箱
#EMAIL_HOST_PASSWORD = '111222333'                  #我的邮箱密码

#EMAIL_HOST_PASSWORD = 'kxoskrxlfwiificf'                  #我的邮箱密码
#EMAIL_SUBJECT_PREFIX = u'[CoorCar网]'            #为邮件Subject-line前缀,默认是'[django]'
#EMAIL_USE_TLS = False                             #与SMTP服务器通信时，是否启动TLS链接(安全链接)。默认是false
#管理员站点
#SERVER_EMAIL = EMAIL_HOST_USER            #The email address that error messages come from, such as those sent to ADMINS and MANAGERS.
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# email config
EMAIL_HOST='smtp.163.com'
EMAIL_PORT = 25                                   #SMTP端口
EMAIL_HOST_USER='guyuanjun92@163.com'
EMAIL_HOST_PASSWORD='gu1992'
EMAIL_USE_TLS = False

#管理员站点
SERVER_EMAIL = EMAIL_HOST_USER            #The email address that error messages come from, such as those sent to ADMINS and MANAGERS.
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
